apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - image: nginx:1.17
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        - name: secret
          mountPath: /opt/secret4.yaml
      volumes:
      - name: config
        configMap:
          name: config5
      - name: secret
        hostPath:
          path: /home/efim/Desktop/Desktop/IBM BigData/Les 7 Kubernetes/homework/secret4.yaml
